- src/userphrase.c
Fix compilation error on VS express
> fix "error C2065: 'ret' : undeclared identifier"

- src/chewingio.c
- src/pinyin.c
- src/userphrase.c
- test/testhelper.c
- test/testhelper.h
I've scanned the project with [cppcheck](http://cppcheck.sourceforge.net/) and done some cleanups. Please take a look.
> Minor cleanups

- src/chewingio.c
- src/porting_layer/src/plat_path.c
- src/tools/init_database.c
- test/testhelper.c
Please review carefully, thanks.
> Covertiy Scan fixes

- src/tools/dump_database.c
- test/testhelper.c
I've scan through all fprintf() calls.
> add line break in fprintf

- src/bopomofo.c
- test/test-bopomofo.c
* bopomofo.c: add and rewrite some comments
* test-bopomofo: update test cases for HSU, ET26, CP26 and PinYin
> Update test cases for KB layout

- CMakeLists.txt
Add a cmake option BUILD_DLL to enable building *.dll with MS VC++.
> Add a cmake option BUILD_DLL to enable building *.dll with MS VC++.

- CMakeLists.txt
This is the only reference I can find: http://blogs.msdn.com/b/vcblog/archive/2014/06/03/visual-studio-14-ctp.aspx
> Fix compilation on MSVC 2015 

- .travis.yml
Also switch builds to use [container infrastructure](https://docs.travis-ci.com/user/workers/container-based-infrastructure/).
> Fix broken TravisCI

- doc/libchewing.texi
> fix typo: Marco -> Macro

- .travis.yml
> Ensure tsi.src is sorted in travis-ci

- src/chewingutil.c
- test/test-bopomofo.c
the setup of bSymbolArrBrkpt is not what we expected.
I modifiy the setup and then it works well.
> Fix jk_selection

- doc/libchewing.texi
- include/chewingio.h
- include/internal/key2pho-private.h
- src/chewingio.c
- src/common/key2pho.c
- test/test-bopomofo.c
> an API to convert phone to bopomofo

- .travis.yml
> Fix locale config in travis-ci setting

- src/chewingio.c
Reduce the redundancy of the code doing the same things
> Reduce redundancy code

- test/stress.c
There exists some indent problem in test/stress.c.
Fix the indent problem and unify indent using 4 spaces.
> Fix indent in test/stress.c

- doc/libchewing.texi
Fix some small problem in doc/libchewing.texi
> Fix documentation

- test/Makefile.am
> Fix `make check` with ./configure --disable-static

- test/randkeystroke.c
Fix the printf() arguments indentation to make it more readable
> Fix printf() arguments indentation

- Cargo.lock
- Cargo.toml
- src/conversion/chewing_conversion.rs
- src/dictionary/layered.rs
Make LayeredDictionary look_phrase a little faster.
> refactor: use fnv hash

- Cargo.lock
- tools/Cargo.toml
- tools/src/bin/init_database.rs
> refac: use argh for init_database

- Cargo.lock
- Cargo.toml
- src/path.rs
> refactor(path): switch to directories-rs

- .github/workflows/ci.yml
So that merge status check only need to look at one check.
> ci: add a summarize step

- README.md
I also remove the first paragraph as it is quite similar to the second paragraph.
Closes https://github.com/chewing/libchewing/issues/433
> Clarify the license as LGPL-2.1-or-later

- CMakeLists.txt
> build: set project language to C

- src/dictionary/loader.rs
- src/dictionary/trie.rs
- tests/test-user-dictionary.rs
>  Ensure user dictionary folder exists before trying to open it

- src/path.rs
> feat(path): ensure data_dir path is defined

- Cargo.toml
- src/capi/io.rs
- src/capi/logger.rs
- src/capi/mod.rs
- src/capi/public.rs
- src/conversion/chewing.rs
- src/conversion/mod.rs
- src/dictionary/kv.rs
- src/dictionary/layered.rs
- src/dictionary/loader.rs
- src/dictionary/mod.rs
- src/dictionary/sqlite.rs
- src/editor/abbrev.rs
- src/editor/composition_editor.rs
- src/editor/estimate.rs
- src/editor/mod.rs
- src/editor/selection/phrase.rs
- src/editor/selection/symbol.rs
- tests/genkeystroke.c
- tests/test-regression.c
> Fix remaining TODOs and FIXMEs

- Cargo.lock
- Cargo.toml
- fuzzer/Cargo.toml
- fuzzer/src/bin/fuzzer.rs
- src/capi/io.rs
- src/capi/logger.rs
- src/conversion/chewing.rs
- src/conversion/mod.rs
- src/editor/composition_editor.rs
- src/editor/mod.rs
- src/editor/selection/phrase.rs
- src/editor/selection/symbol.rs
- src/lib.rs
- tests/test-bopomofo.c
> refactor(conv): rework composition abstraction

- src/dictionary/sqlite.rs
> feat(dict): set SQLite application_id and user_version

- CMakeLists.txt
- src/path.rs
> feat: define CHEWING_DATADIR environment variable to override sys path

- Cargo.lock
- src/zhuyin/bopomofo.rs
- src/zhuyin/syllable.rs
- tools/Cargo.toml
- tools/src/dump.rs
- tools/src/flags.rs
- tools/src/init_database.rs
> feat(cli): allow dump and import CSV file

- src/conversion/chewing.rs
- src/conversion/mod.rs
- src/dictionary/cdb.rs
- src/dictionary/kv.rs
- src/dictionary/loader.rs
- src/dictionary/mod.rs
- src/dictionary/trie.rs
- src/dictionary/uhash.rs
- src/editor/abbrev.rs
- src/editor/mod.rs
- src/editor/selection/phrase.rs
- src/editor/selection/symbol.rs
- src/editor/syllable/pinyin.rs
- src/zhuyin/syllable.rs
> refactor: fix some clippy warnings

- README.md
> docs: update build instruction and Rust MSRV info

- src/conversion/chewing.rs
> refactor(conv): Replace brute force algorithm with one with upper bound

- CMakeLists.txt
- CMakePresets.json
- Cargo.lock
- NEWS
- capi/Cargo.toml
- fuzzer/Cargo.toml
- vet/audits.toml
- vet/config.toml
- vet/imports.lock
> build: try to use system provided corrosion-rs first

- fuzzer/src/bin/fuzzer.rs
> test(fuzzing): Add more API calls to fuzzer

- NEWS
- capi/src/io.rs
- capi/src/public.rs
- src/editor/composition_editor.rs
- src/editor/mod.rs
- tests/test-bopomofo.c
- tests/test-regression.c
Fixes #513, fixes #514, fixes #512, fixes #511
> Collectioin of 0.8.0-rc.2 bug fixes

- Cargo.toml
- capi/src/io.rs
- src/conversion/chewing.rs
The new algorithm is fast enough so we can simplify the code a bit.
> refactor(conv): Keep only the graph search based algorithm

- .github/workflows/ci.yml
- NEWS
- capi/src/io.rs
- tests/testhelper/src/path.rs
> Fix FTBFS on aarch64

- AUTHORS
- NEWS
#538 
fixed several typos in the NEWS file and overall syntax consistency.
> fix: typos in NEWS

- .github/ISSUE_TEMPLATE/release-checklist.md
- .github/workflows/ci.yml
- NEWS
- src/editor/zhuyin_layout/hsu.rs
- tests/test-bopomofo.c
> Fix Hsu keyboard fuzz conversion (ㄍㄧ to ㄐㄧ and ㄍㄩ to ㄐㄩ)

- .github/workflows/ci.yml
This reverts commit b98e3971352184af41427bf5f9df3525ace2cf42.
Fixes #540
> Revert "ci: Run test on macos-14 which is a aarch64 platform"

- src/editor/zhuyin_layout/hsu.rs
- tests/test-bopomofo.c
> Fix Hsu keyboard conversion and add more tests

- NEWS
- capi/src/io.rs
- tests/test-bopomofo.c
- tests/test-config.c
> fix(capi): Config options were incorrectly reset after certain operations

- src/editor/mod.rs
- tests/test-bopomofo.c
> feat(editor)!: Merge DOWN and SPACE key behavior in pagination

- capi/src/io.rs
- src/editor/mod.rs
- tests/test-bopomofo.c
- tests/test-config.c
> feat(editor): Add an option to disable fullwidth toggle key

- capi/src/version.rs
- include/chewing.h
> feat(capi): Define version macros

- src/editor/mod.rs
- tests/test-bopomofo.c
> feat(editor): Automatic snapshot selections when the curser is moved

- CMakeLists.txt
- include/chewing-compat.h
- include/chewingio.h
- include/global.h
- include/mod_aux.h
> fix(capi): Ship 0.5.x compat headers

- tools/src/init_database.rs
chewing-cli 在解析的時候，允許多個空白。
解析的行為跟之前有一點不一樣：逗號如果出現在後面注音符號的部份，一樣會被當成分隔符。不知道有沒有關係。
Close #656.
> feat(cli): allow multiple whitespace in dictionary source file

- capi/src/io.rs
> fix: correctly allocate and free array returned to C FFI

- tests/CMakeLists.txt
- tools/src/flags.rs
- tools/src/init_database.rs
> feat(cli): add --fix option to fix simple errors

- src/dictionary/layered.rs
- src/editor/estimate.rs
- src/editor/mod.rs
Fixes https://github.com/chewing/windows-chewing-tsf/issues/368
> dict: ensure userphrase takes precedence

- NEWS
- capi/src/io.rs
- capi/src/lib.rs
- src/editor/mod.rs
- tests/test-bopomofo.c
- tests/test-keyboardless.c
> Fix a couple compatibility bugs

- NEWS
> dict: fix 風靡 missing bopomofo
