src/Makefile.am, src/porting_layer/src/Makefile.am, src/porting_layer/src/plat_path.c
This fixes the problem that causes chewing_new to return NULL when building
with CMake. Close #178.
=> Fix inconsistent CHEWING_DATADIR definition

src/chewingutil.c, test/test-bopomofo.c
This patch fixes issue #160.
The bug is caused by an out-of-date `pgdata->symbolKeyBuf` in `ChewingKillChar`. We simply remove the symbol key which corresponds to `chiSymbolCursorToKill`.
=> Fix ChewingKillChar which is disabling OpenSymbolChoice

src/bopomofo.c, test/test-keyboard.c
Because Hsu and ET26 map multiple bopomofo 
into one single key, therefore, if a consonant or 
a medial already exists in buffer, and the user 
presses a key with consonant and rhyme, libchewing 
should consider that the user wants to input the rhyme.
=> Fix #170 (ㄅ cannot overwrite ㄆ in HSU and ET26)

contrib/python/chewing.py
Add platform check and if we're in Windows, load *.dll instead of *.so.
The current directory containing the python module is searched first.
=> Make the python binding of libchewing support Windows dll files.

include/global.h
Removed unicode characters in the file
=> Fix MSVC warning C4819

test/stress.c
1. unistd.h does not exist in MSVC
2. MSVC does not define SIGSTOP: https://msdn.microsoft.com/en-us/library/5s651ehs.aspx
3. change BSD `random()` to C standard library function `rand()`
=> Fix compilation on MSVC2015

doc/libchewing.texi, include/internal/bopomofo-private.h, include/internal/chewing-private.h, src/chewingio.c, src/common/key2pho.c, test/test-keyboard.c
The Carpalx keyboard layout was recently added to xkeyboard-config and kbd.
[xkeyboard-config](https://bugs.freedesktop.org/show_bug.cgi?id=94723)
[kbd](http://git.altlinux.org/people/legion/packages/kbd.git?p=kbd.git;a=commit;h=9ae1585479ab2a68c030790320ca45892cb6ea27)
It would be nice to not have to use a locally-patched version of libchewing to be able to type in Chinese.
Thanks,
=> Add Carpalx keyboard layout support

src/chewingio.c, test/testhelper.c, test/testhelper.h
=> Implement has_userphrase with chewing_userphrase_lookup

src/choice.c, test/test-bopomofo.c
倚天26鍵和許氏鍵盤相同，將兩個注音符號配置到同一鍵，
所以要將其中一個的候選字加到另一個的清單中。
libchewing 已經實做許氏的部份，現在加上倚天26鍵。
- src/choice.c
Add ET26 to ChoiceInfoAppendChi()
- test/test-bopomofo.c
Update test cases for both ET26 and HSU
=> Fix #235: Unable to input some Bopomofos with ET26 layout

src/userphrase-hash.c, test/test-userphrase.c
When a userphrase which has cascading items to be removed by chewing_userphrase_remove,
all of these cascading items will be freed in FreeHashItem.
However, the TerminateUserphrase  will also try to use FreeHashItem to release these items again in chewing_delete.
It causes malloc error: "pointer being freed was not allocated" on macOS.
This PR is to isolate the userphrase-to-be-removed by setting its next-ptr to be NULL.
As for its cascading items, they will be freed by TerminateUserphrase.
```
#include <chewing.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <unistd.h>
int main (void)
{
ChewingContext *ctx = NULL;
const char p1[] = "測";
const char p2[] = "冊";
const char b[]  = "ㄘㄜˋ";
ctx = chewing_new();
chewing_userphrase_add(ctx, p1, b); …
```
=> userphrase-hash: avoid double free in TerminateUserphrase

src/choice.c
The chiSymbolCursor should be placed back to old position no matter which type of choice selection is finished.
The original expression wants to check the type of choice, then set the chiSymbolCursor to old position, but the expression is always true. The chiSymbolCursor should place back to old position after finishing the choice selection in any case, so removing the if statement.
=> Fix ChoiceEndChoice expression always true

src/bopomofo.c, test/test-bopomofo.c
1. 增補ㄓㄔㄕ→ㄐㄑㄒ轉換。
許氏的ㄐㄑㄒ和ㄓㄔㄕ是在同一個按鍵，有介音ㄧ或ㄩ的時候，ㄓㄔㄕ才會轉換成ㄐㄑㄒ。但目前 libchewing 只有ㄐㄑㄒ轉ㄓㄔㄕ，沒有ㄓㄔㄕ轉ㄐㄑㄒ。因此，若使用者先輸入韻母才輸入介音，就無法正確的出字。例如：使用者想輸入「鄉」，但在快速打字的時候出錯，順序變成 ``ㄒ → ㄤ → 一``，這時ㄒ會因為ㄤ而轉換成ㄕ，等到輸入ㄧ的時候卻沒有再換回ㄒ，變成 ``ㄕㄧㄤ``。[1]
2. 按下 jvc 時，優先輸出ㄓㄔㄕ。
ㄓㄔㄕ本身加聲調就可以出字，而ㄐㄑㄒ不行。但目前 libchewing 是按下 jvc 鍵時先輸出ㄐㄑㄒ到預編區，等按聲調的時候才轉換成ㄓㄔㄕ，所以使用者看見的是輸入ㄐ卻得到ㄓ的字（之、知、隻等等），這樣比較不直覺，也和自然輸入法的行為相反，所以改為先輸出ㄓㄔㄕ。
3. 更新 test case。
[1] https://groups.google.com/d/msg/chewing-devel/D8MMq_sRxnU/KZ3ucglaAAAJ
=> Update jvc-convert of KB layout Hsu

src/choice.c, test/test-userphrase.c
* src/choice.c
Currently, after users select a candidate on the list, libchewing
saves it as an one-word-phrase into the userphrase bank. However,
this is not desirable, especially when the users picked a wrong
candidte.
Libchewing should learn phrases only after the users press
Enter and commit.
This also prevents the userphrase database from growing fast.
* test/test-userphrase.c
Fix and update test cases.
=> Auto learn phrases only after committing

doc/libchewing.texi, include/chewingio.h, include/global.h, src/chewingio.c, src/compat.c, test/test-config.c, test/test-struct-size.c, test/test-userphrase.c
Dear All,
I'm wondering if we can add a switch that allows users to disable the automatic learning function, like the 微軟新注音. 
This would be useful for users who want to keep their user-phrase database slim and organized.
Besides, ibus-chewing would need this feature for the 簡單注音模式. Under this mode, every single character that users input is stored into the user-phrase database.
Hopefully I did it correctly. Thanks!
=> Implement chewing_set_autoLearn() and chewing_get_autoLearn()

include/internal/hash-private.h, src/hash.c, src/userphrase-hash.c, test/test-userphrase.c
When a userphrase is going to be removed, HashModify calculates the offset according to its item_index.
```
pItem->item_index * FIELD_SIZE + 4 + strlen(BIN_HASH_SIG)
```
However, the item_index will be shifted if there has previously removed item in uhash.dat.
Considering the following example:
chewing_userphrase_add(ctx, p1, b)
chewing_userphrase_add(ctx, p2, b)
| item_index | wordSeq | offset in uhash.dat |
| ---------- | ------- | ------------------- |
| 0          | p1      | 8                   |
| 1          | p2      | 133                 |
chewing_userphrase_remove(ctx, p1, b)
| item_index | wordSeq | offset in uhash.dat |
| ---------- | ------- | ------------------- |
|            | p1'     | 8                   |
| 1          | p2      | 133                 |
When libchewing …
=> hash: fix hash item offset calculating in uhash.dat

src/chewingio.c, test/test-bopomofo.c
The pre-edit buffer is empty, which means there's no need to open candidate list, chewing_handle_Space() should output a space.
=> Fix: chewing_handle_Space() cannot input space when buffer is empty

.travis.yml
While the libchewing requires cmake version equal or higher then 2.8.8, but the default cmake version in Travis-CI is 2.8.7.
Install cmake from kalakris/cmake for higher version cmake.
=> Travis-CI install higher version of cmake

.travis.yml, configure.ac
Since Aug 2017, Ubuntu Trusty is the default, and the official cmake is
new enough (2.8.12.2) - drop cmake PPA stuffs.
Also actually uses container-based instances for faster builds.
[1] https://docs.travis-ci.com/user/reference/overview/
=> Fix Travis-CI builds

contrib/python/chewing.py
The old code will segfault on platforms with 64bit pointer like x86_64.
=> chewing.py supports platforms with 64bit pointer

data/CMakeLists.txt
From version 3.6, CMake supports cross compiling to other architectures
with an emulator. In order to do that, the command must be starts with
a target built by CMake.
Let move the creation of data directory to configure phase, change the
command to exactly what CMake need, and use WORKING_DIRECTORY in
add_custom_command instead of using chdir. All of those commands are
available at CMake 2.8.8 (the oldest version that is supported).
=> build: cmake: support cross compiling with qemu

capi/chewing-internal/include/chewing_internal.h, capi/chewing-internal/src/types.rs, capi/chewing-public/include/chewing_rs.h, capi/chewing-public/src/types.rs, include/global.h, include/internal/chewing-private.h, src/chewingio.c, src/compat.c, test/test-struct-size.c
Testing:
* `chewing_set_autoLearn(ctx, AUTOLEARN_DISABLED)` still works
* Either libchewing-git with or without WITH_RUST has identical ABI as libchewing 0.5.1
=> Make the ABI consistent with 0.5.1

Cargo.lock, Cargo.toml, src/dictionary/trie.rs
It turns out we don't yet need to handle complex binary layout.
Reading from the slice is slightly faster. Also changed to use exact sized chunks iterator.
=> Remove the binary-layout dependency

src/hash.c
The change should be also applied to hash.c to compile libchewing without sqlite3.
=> Do member name change of ChewingData in hash.c

Cargo.lock, Cargo.toml, src/conversion/chewing_conversion.rs, src/dictionary/layered.rs, src/dictionary/trie.rs
The original trie node layout is less optimal.
=> refactor(trie): use smaller trie nodes and guarantee aligned memory access

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, rust-toolchain.toml
1. add devcontainer support
+ `cargo test`
+ `cargo fmt`
+ `cargo clippy`
+ `cargo check`
+ Build with rust
+ `cmake -B build -DCMAKE_BUILD_TYPE=Release -DWITH_RUST=ON`
+ `cmake --build ./build -v --config Release`
+ `cd build && ctest -C Release --output-on-failure`
+ Build without rust
+ `cmake -B build -DCMAKE_BUILD_TYPE=Release`
+ `cmake --build ./build -v --config Release`
+ `cd build && ctest -C Release --output-on-failure`
=> feat: add devcontainer support

src/tools/init_database.c
Closes https://github.com/chewing/libchewing/issues/334
=> Correctly read phrase frequencies for sorting

.cargo/config.toml, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, xtask/Cargo.toml, xtask/src/cli.rs, xtask/src/main.rs
Ref: #399 
This PR wraps cmake and other build systems within `cargo xtask` to simplify the build and test processes.
We only expose build options that developer would care while developing.
Notes:
1. `cargo xtask --help` will show available subcommands
2. `cargo xtask build --help` will show available build options
3. `cargo xtask test --help` will show available test options
=> feat: using cargo xtask for build & testing

.github/workflows/ci.yml, CMakeLists.txt, Cargo.toml, capi/chewing-internal/include/chewing_internal.h, capi/chewing-internal/src/types.rs, capi/chewing-internal/src/userphrase.rs, rust-toolchain.toml, src/chewingio.c
Don't enforce local rust version with rust-toolchain.toml so that we can use latest stable for development.
Test MSRV explicitly in CI instead.
=> build: test both msrv and stable rust

Cargo.lock, Cargo.toml, capi/chewing-internal/Cargo.toml, capi/chewing-public/Cargo.toml, src/dictionary/trie.rs, tools/Cargo.toml, xtask/Cargo.toml
Update dependencies after we bump the MSRV to 1.64
Also solves two minor vulnerabilities.
=> chore: update dependencies

test/test-config.c
The default value testing for bAutoLearn is not added.
=> Add default config test for autoLearn option

AUTHORS
* Put my old and new names in the same line
* Remove my email address to avoid spam mails
Removing my email address should not not affect communication. If someone wants to contact me for libchewing-related discussions, mention me (@yan12125) on a GitHub issue/pull request works.
=> Update contributor information

include/internal/bopomofo-private.h, src/bopomofo.c, src/chewingutil.c
As discuss in #412, we should fix pinyin keyboard if statement.
Add a helper function `BopomofoKbIsPinyin(BopomofoData *)` to achieve this.
=> fix: pinyin keyboard detection should not depend on enum ordering

capi/src/io.rs, tests/testhelper.c
=> fix(capi): chewing_cand_CheckDone result was reversed in capi

src/editor/mod.rs, tests/test-regression.c
=> fix(editor): Correctly ignore instead of absorb keys when the pre-edit buffer is empty

.github/workflows/dependabot.yml
The current configuration will present a PR (monthly) to bump Action versions used in "Github Actions" script. This will help keeping the Action versions up to date.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates
=> Introduce dependabot version updates

CMakeLists.txt
would be also good to not run tests for the downstream packaging (as it is already done by CI)
relates to https://github.com/Homebrew/homebrew-core/pull/172332
=> chore(build): add option to turn off tests run

CMakeLists.txt, ChewingConfig.cmake.in
Downstream projects will now be able to find libchewing via CMake with the following:
```cmake
find_package(Chewing REQUIRED)
target_link_libraries(someTarget PRIVATE Chewing::libchewing)
```
https://cmake.org/cmake/help/latest/guide/tutorial/Adding%20Export%20Configuration.html
=> Generate CMake package files

CMakePresets.json, data/CMakeLists.txt
In such cases, WITH_RUST is not defined, and thus wrong CMake commands in data/CMakeLists.txt are used.
This is a follow-up of https://github.com/chewing/libchewing/pull/567, where the CMake option WITH_RUST is gone.
=> build: fix building without using CMake presets

NEWS, data/CMakeLists.txt
=> build: Fix installation of static data when not building tests

src/zhuyin/bopomofo.rs
Fix https://github.com/chewing/libchewing/issues/367.
- Removed all TODO and added the missing documents.
- Add trivia to make enum variants document layout slightly better.
=> Update documentation in bopomofo module

src/editor/zhuyin_layout/pinyin.rs
Fixes #585 
Introduced in v0.8.0
=> Fix Hanyu Pinyin's empty rime handling

CMakeLists.txt, src/editor/keyboard/mod.rs, src/editor/mod.rs, src/editor/zhuyin_layout/pinyin.rs, tests/test-bopomofo.c
=> fix(editor): printable non A-Z chars should output symbols in pinyin

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, README.md, capi/Cargo.toml, capi/src/io.rs, capi/src/lib.rs, capi/src/symbols-elf.map, capi/src/symbols-mach_o.map, capi/src/symbols-msvc.def, capi/src/version.rs, fuzzer/Cargo.toml, include/chewing.h, tests/test-config.c, tests/testhelper/Cargo.toml, tools/Cargo.toml
=> feat(capi): Add API to get runtime library version

src/editor/zhuyin_layout/pinyin.rs
=> fix(editor)!: separate special handling by pinyin variants

CMakeLists.txt
Fixes #602 
I didn't use theo `--whole-archive` option because it messes with linking on Windows 😞
=> build: force linking chewing_version obj file

capi/src/io.rs, capi/src/lib.rs, capi/src/public.rs, include/chewing.h, src/editor/keyboard/mod.rs, src/editor/keyboard/workman.rs, src/editor/zhuyin_layout/mod.rs, tests/test-keyboard.c
=> feat(editor): Add workman layout support

src/editor/mod.rs, tests/genkeystroke.c, tests/test-bopomofo.c
=> feat(editor): Show notification about mode switches triggered by input

capi/src/io.rs, capi/src/lib.rs, capi/src/symbols-elf.map, capi/src/symbols-mach_o.map, capi/src/symbols-msvc.def, include/chewing.h, src/editor/mod.rs, tests/test-bopomofo.c
=> feat(capi): New API chewing_ack to acknowledge output buffers

src/conversion/chewing.rs, src/conversion/fuzzy.rs, src/conversion/mod.rs, src/dictionary/loader.rs, src/dictionary/mod.rs, src/dictionary/trie_buf.rs, src/editor/estimate.rs, src/zhuyin/syllable.rs
Fixes #361 
Fixes #362 
Fixes #363 
Fixes #364 
Fixes #365 
Fixes #366 
Fixes #368
=> docs: Add docs for some modules

tools/src/init_database.rs
=> fix(data): Default dictionary fixes

src/editor/zhuyin_layout/hsu.rs, src/editor/zhuyin_layout/pinyin.rs
Add some information about PinyinVariant
=> add basic PinyinVariant info

README.md
I'm fairly sure Workman already exists as an available layout.
=> docs: Add Workman to README.md

src/conversion/chewing.rs
Found via https://github.com/chewing/windows-chewing-tsf/issues/276
=> fix: skip zero-length phrases

src/conversion/chewing.rs, tests/test-bopomofo.c
Remove weighted heuristics. Use log probability calculated from dictionary.
=> refactor: use less heuristic in path scoring

doc/CMakeLists.txt
Some Linux distributions compresses man-pages with different archiver. Add option for controlling compressing man-pages. On `-DCOMPRESS_MANS=OFF` man-pages installed as is and compressed by packager separately.
=> Add option for compressing man-pages
